#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "03.00 basic packages"

# logline "03.01 add repos"
# yum -d1 -y install epel-release
# yum -d1 -y install wget
# if [ "$OS_VERSION" = "8" ]; then
#     logline "03.02 Loading remi-release-8 for centos 8"
#     dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
# else
#     logline "03.02 Loading remi-release-9 for centos 9"
#     dnf install -y https://rpms.remirepo.net/enterprise/remi-release-9.rpm
# fi

# yum -q repolist

logline "03.03 update system - this can take a while.."
DEBIAN_FRONTEND=noninteractive apt update && apt upgrade -y

logline "03.04 apt some sysop and dev tools"
apt install -qq -y htop iotop ncdu pv unzip build-essential autoconf automake git 

logline "03.05 apt some extra tools"
# ufw is firewall
apt install -qq -y ufw

# this is for hypervisor so VM manager knows us
apt install -qq -y acpid  cloud-init

systemctl enable acpid
systemctl start acpid

logline "03.05 apt Sury repo"
# Install dependencies
apt install -y apt-transport-https lsb-release ca-certificates curl
# Add Sury GPG key
curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg
# Add repository
echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
# Update
apt update

logline "03.96 add gh command to git for push to github (origin)"
git config --global alias.gh '!f() { git add -A && git commit -m "${@:-incremental}" && git push; }; f'


logline "03.99 basic packages END"
