#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "04.00 start root security"
logline "04.01 secure password or locked password"

# flush keyboard buffer
while read -t 1 garbage; do sleep 0; done

# $rootpas is normally pre-asked in parts/02_set_hostname so this part can run
# unattended. Fall back to prompting here when the script is executed standalone.
# Use ${var+set} so a deliberate empty answer (= default) is NOT re-prompted.
if [ -z "${rootpas+set}" ]; then
	echo -n "Do you want a long secure root password (l) or no password at all (n) [N/l]=>" && read rootpas
fi
if [ "$rootpas" = "l" ]; then 
	## create long (emergency) password for root
	newpas=`tr -dc A-Z-a-z0-9 < /dev/urandom | head -c${1:-32}`
	echo $newpas | passwd root --stdin
	echo ">>>>>>>>> ROOT password set to $newpas - you might want to write this down"
	echo -n "Enter to continue >" && read 
else
		passwd root -l	
fi
logline "04.99 root secured"


