#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "06.00 global settings START"
# flush keyboard buffer
while read -t 1 garbage; do sleep 0; done


## set local timezone
logline "06.02 set local timezone"
# $timezone is normally pre-asked in parts/02_set_hostname (blank == UTC).
# Use ${var+set} to detect "asked but blank" vs "never asked".
if [ -z "${timezone+set}" ]; then
	echo -n "What timezone do you want (enter for UTC) =>"
	read timezone
fi
if [ "$timezone" == "" ]; then
	timedatectl set-timezone UTC
else
	timedatectl set-timezone $timezone
fi

logline "06.03 set locales"
apt install locales-all
update-locale LANG=en_US.UTF-8

logline "06.04 Python 3 - add the stuff we need"
apt install -y python3 python3-pip python3-dev python3-venv
# make sure there is 'python' (not only python3)
apt install python-is-python3

### fortune and cowsay (just for fun on login)
# $docowsay is normally pre-asked in parts/02_set_hostname so this part can run
# unattended. Fall back to prompting here when the script is executed standalone.
# Use ${var+set} so a deliberate empty answer (= default "yes") is NOT re-prompted.
if [ -z "${docowsay+set}" ]; then
	echo -n "Install fortune+cowsay banner on login (just for fun) [Y/n]=>" && read docowsay
fi
if [ ! "$docowsay" = "n" ]; then
	logline "06.04 install fortune and cowsay"
	# fortune is now a python app (fortune-mod is no longer distributed and a pain to cmake)
	# pip3 install fortune
	apt install -y fortune-mod
	#git clone https://github.com/bmc/fortunes.git /usr/local/share/fortunes
	#yum -y install cowsay
	# need to install from source..

	cd /usr/local/src
	git clone https://github.com/schacon/cowsay.git
	cd cowsay
	# install.sh prompts for a target directory; piping a newline accepts the default
	# (use `yes "" | sh install.sh` if it ever grows additional prompts)
	echo | sh install.sh
	cd $INSTALLPWD
	su - $username -c 'echo "fortune | cowsay -W 100 -f small" >> ~/.bashrc'
fi

logline "06.05 additional installs"
apt install -y rsync

logline "06.99 global settings END"
 

