#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "06.00 global settings START"
# flush keyboard buffer
while read -t 1 garbage; do sleep 0; done


## set local timezone
logline "06.02 set local timezone"
echo -n "What timezone do you want (enter for UTC) =>"
read timezone
if [ "$timezone" == "" ]; then
	timedatectl set-timezone UTC
else
	timedatectl set-timezone $timezone
fi

logline "06.04 Python 3 - add the stuff we need"
apt install -y python3 python3-pip python3-dev python3-venv

### yum fortune and cowsay
logline "06.04 install fortune and cowsay"
# fortune is now a python app (fortune-mod is no longer distributed and a pain to cmake)
# pip3 install fortune
apt install -y fortune-mod
#git clone https://github.com/bmc/fortunes.git /usr/local/share/fortunes
#yum -y install cowsay
# need to install from source..

cd /usr/local/src
git clone https://github.com/schacon/cowsay.git
cd cowsay
sh install.sh
cd $INSTALLPWD
echo "fortune | cowsay -W 100 -f small" >/etc/profile.d/cowsay.sh

logline "06.05 additional installs"
apt install -y rsync

logline "06.99 global settings END"
 

