#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "09.00 mariadb mysql START"
echo -n "MYSQL (MARIADB) is optional. Install mariadb [Y/n]=>" && read domysql
if [ ! "$domysql" = "n" ]; then

  logline "09.01 apt mariadb"

  apt install -y mariadb-server mariadb-client

  logline "09.02 enable and start"
  systemctl enable mariadb
  systemctl start mariadb

  logline "09.03 make mysql secure"
  echo "#################### MariaDB secure installation is going to ask some questions"
  echo "#################### The current password is still empty, just press enter when asked for"
  /usr/bin/mysql_secure_installation

fi

logline "09.99 mariadb END"

