#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "10.00 nginx START"

logline "10.01 apt nginx"
apt install -y nginx

# need to add php to the default nginx config
sed -i 's/index index.html index.htm index.nginx-debian.html;/index index.php index.html index.htm;/' /etc/nginx/sites-available/default


systemctl enable nginx
systemctl start nginx

logline "10.02 Create vhost-enable and vhost-disable for easy tweaking"
TOOLDIR=/usr/local/bin
# lets create an enable and disable command
cat <<-'EOF' >$TOOLDIR/vhost-enable
	#!/bin/bash
	ln -s /etc/nginx/sites-available/$1 /etc/nginx/sites-enabled/$1
EOF
chmod a+x $TOOLDIR/vhost-enable
cat <<-'EOF' >$TOOLDIR/vhost-disable
	#!/bin/bash
	rm /etc/nginx/sites-enabled/$1
EOF
chmod a+x $TOOLDIR/vhost-disable

logline "10.06 create a default landing page for the machine"
cp -R ${BASH_SOURCE%/*}/assets/homepage/* /var/www/html

logline "10.99 nginx END"

