#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "12.00 redis START"

logline "12.01 Redis Server install"
echo -n "redis installation is optional. Install Redis [Y/n]=>" && read doredis
if [ ! "$doredis" == "n" ]; then
	logline "12.02 Installing redis"
	apt install -y redis-server

	systemctl enable redis-server
	systemctl start redis-server
	logline "12.02 Redis Server test"
	redis-cli ping
fi

logline "12.99 redis END"

